# Generated by Django 3.0.4 on 2020-03-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='place',
        ),
    ]
