# Generated by Django 2.2 on 2020-04-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='planner',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
