# Generated by Django 3.0.4 on 2020-04-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0002_remove_booking_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trainWellApp.Place'),
        ),
    ]
