# Generated by Django 3.0.4 on 2020-04-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0002_auto_20200408_1101'),
        ('trainWellApp', '0003_booking_place'),
    ]

    operations = [
    ]
