# Generated by Django 3.0.4 on 2020-04-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0003_booking_place'),
        ('trainWellApp', '0002_auto_20200408_1101'),
    ]

    operations = [
    ]
