# Generated by Django 3.0.4 on 2020-04-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0004_merge_20200412_0914'),
        ('trainWellApp', '0006_auto_20200412_2347'),
    ]

    operations = [
    ]
