# Generated by Django 3.0.4 on 2020-05-01 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainWellApp', '0008_planner_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Incidence',
            name="created",
        ),
    ]
