# Generated by Django 3.0.4 on 2020-04-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0008_planner_is_staff'),
        ('trainWellApp', '0008_incidence'),
    ]

    operations = [
    ]
