# Generated by Django 3.0.4 on 2020-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trainWellApp', '0009_merge_20200430_2324'),
    ]

    operations = [
    ]
