# Generated by Django 3.0.4 on 2020-05-02 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0009_incidence'),
        ('trainWellApp', '0010_incidence_places'),
    ]

    operations = [
    ]
