# Generated by Django 3.0.4 on 2020-05-02 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0011_merge_20200502_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidence',
            name='places',
            field=models.ManyToManyField(to='trainWellApp.Place'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='description',
            field=models.TextField(),
        ),
    ]
