# Generated by Django 3.0.4 on 2020-05-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0012_auto_20200502_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#cc73e1', max_length=16),
        ),
    ]
