# Generated by Django 3.0.4 on 2020-05-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0014_merge_20200506_2003'),
        ('trainWellApp', '0015_notification_is_read'),
        ('trainWellApp', '0014_planner_is_gerent'),
    ]

    operations = [
    ]
