# Generated by Django 3.0.4 on 2020-05-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0016_merge_20200507_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='booking_state',
            field=models.PositiveIntegerField(choices=[(1, 'Pagada'), (2, 'Impagada'), (3, 'Cancelada pagada'), (4, 'Cancelada impagada'), (5, 'Cancelada fora de termini')], default=2),
        ),
    ]
