# Generated by Django 3.0.4 on 2020-05-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0017_invoice_booking_states'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='booking_states',
            new_name='booking_state',
        ),
    ]
