# Generated by Django 2.2.12 on 2020-05-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0017_invoice_booking_state'),
        ('trainWellApp', '0018_auto_20200515_0937'),
    ]

    operations = [
    ]
