# Generated by Django 2.2.12 on 2020-05-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0018_auto_20200515_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, 'USER'), (2, 'ADMIN')], default=1),
        ),
    ]
