# Generated by Django 2.2.12 on 2020-05-11 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0018_auto_20200511_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
