# Generated by Django 2.2.12 on 2020-05-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0019_auto_20200511_1904'),
        ('trainWellApp', '0018_auto_20200512_1941'),
    ]

    operations = [
    ]
