# Generated by Django 2.2.12 on 2020-05-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0021_auto_20200518_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='shape',
            field=models.ImageField(blank=True, default='place_images/default.png', null=True, upload_to='place_shapes/'),
        ),
    ]
