# Generated by Django 3.0.6 on 2020-05-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainWellApp', '0025_auto_20200525_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
    ]
